# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer0.singledomain.com:
    container_name: orderer0.singledomain.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/singledomain.com/orderers/orderer0.singledomain.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/singledomain.com/orderers/orderer0.singledomain.com/tls/:/var/hyperledger/orderer/tls
        - orderer0.singledomain.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  p0.org1.singledomain.com:
    container_name: p0.org1.singledomain.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=p0.org1.singledomain.com
      - CORE_PEER_ADDRESS=p0.org1.singledomain.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=p0.org1.singledomain.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=p1.org1.singledomain.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=p0.org1.singledomain.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=password

    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org1.singledomain.com/peers/p0.org1.singledomain.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org1.singledomain.com/peers/p0.org1.singledomain.com/tls:/etc/hyperledger/fabric/tls
        - p0.org1.singledomain.com:/var/hyperledger/production
    ports:
      - 7051:7051

  p1.org1.singledomain.com:
    container_name: p1.org1.singledomain.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=p1.org1.singledomain.com
      - CORE_PEER_ADDRESS=p1.org1.singledomain.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=p1.org1.singledomain.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=p1.org1.singledomain.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=p0.org1.singledomain.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=password

    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org1.singledomain.com/peers/p1.org1.singledomain.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org1.singledomain.com/peers/p1.org1.singledomain.com/tls:/etc/hyperledger/fabric/tls
        - p1.org1.singledomain.com:/var/hyperledger/production

    ports:
      - 8051:8051

  p0.org2.singledomain.com:
    container_name: p0.org2.singledomain.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=p0.org2.singledomain.com
      - CORE_PEER_ADDRESS=p0.org2.singledomain.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=p0.org2.singledomain.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=p0.org2.singledomain.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=p1.org2.singledomain.com:10051
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=password

    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org2.singledomain.com/peers/p0.org2.singledomain.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org2.singledomain.com/peers/p0.org2.singledomain.com/tls:/etc/hyperledger/fabric/tls
        - p0.org2.singledomain.com:/var/hyperledger/production
    ports:
      - 9051:9051

  p1.org2.singledomain.com:
    container_name: p1.org2.singledomain.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=p1.org2.singledomain.com
      - CORE_PEER_ADDRESS=p1.org2.singledomain.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=p1.org2.singledomain.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=p1.org2.singledomain.com:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=p0.org2.singledomain.com:9051
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb3:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=password

    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org2.singledomain.com/peers/p1.org2.singledomain.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org2.singledomain.com/peers/p1.org2.singledomain.com/tls:/etc/hyperledger/fabric/tls
        - p1.org2.singledomain.com:/var/hyperledger/production
    ports:
      - 10051:10051

# <!-- BEGIN Peer0 - Adding  -->
  p0.org3.singledomain.com:
      container_name: p0.org3.singledomain.com
      extends:
        file: peer-base.yaml
        service: peer-base
      environment:
        - CORE_PEER_ID=p0.org3.singledomain.com
        - CORE_PEER_ADDRESS=p0.org3.singledomain.com:11051
        - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
        - CORE_PEER_CHAINCODEADDRESS=p0.org3.singledomain.com:11052
        - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
        - CORE_PEER_GOSSIP_EXTERNALENDPOINT=p0.org3.singledomain.com:11051
        - CORE_PEER_GOSSIP_BOOTSTRAP=p1.org3.singledomain.com:12051
        - CORE_PEER_LOCALMSPID={Org3MSP
        - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
        - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2:5984
        # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
        # provide the credentials for ledger to connect to CouchDB.  The username and password must
        # match the username and password set for the associated CouchDB.
        - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
        - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=password
      
      volumes:
          - /var/run/:/host/var/run/
          - ../crypto-config/peerOrganizations/org3.singledomain.com/peers/p0.org3.singledomain.com/msp:/etc/hyperledger/fabric/msp
          - ../crypto-config/peerOrganizations/org3.singledomain.com/peers/p0.org3.singledomain.com/tls:/etc/hyperledger/fabric/tls
          - p0.org3.singledomain.com:/var/hyperledger/production
      ports:
        - 11051:11051
# <!-- END Peer0 - Adding  -->
# <!-- BEGIN Peer1 - Adding  -->
  p1.org3.singledomain.com:
      container_name: p1.org3.singledomain.com
      extends:
        file: peer-base.yaml
        service: peer-base
      environment:
        - CORE_PEER_ID=p1.org3.singledomain.com
        - CORE_PEER_ADDRESS=p1.org3.singledomain.com:12051
        - CORE_PEER_LISTENADDRESS=0.0.0.0:12051
        - CORE_PEER_CHAINCODEADDRESS=p1.org3.singledomain.com:12052
        - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:12052
        - CORE_PEER_GOSSIP_EXTERNALENDPOINT=p1.org3.singledomain.com:12051
        - CORE_PEER_GOSSIP_BOOTSTRAP=p0.org3.singledomain.com:11051
        - CORE_PEER_LOCALMSPID=Org3MSP
        - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
        - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb3:5984
        # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
        # provide the credentials for ledger to connect to CouchDB.  The username and password must
        # match the username and password set for the associated CouchDB.
        - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
        - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=password
  
      volumes:
          - /var/run/:/host/var/run/
          - ../crypto-config/peerOrganizations/org3.singledomain.com/peers/p1.org3.singledomain.com/msp:/etc/hyperledger/fabric/msp
          - ../crypto-config/peerOrganizations/org3.singledomain.com/peers/p1.org3.singledomain.com/tls:/etc/hyperledger/fabric/tls
          - p1.org3.singledomain.com:/var/hyperledger/production
      ports:
        - 12051:12051
# <!-- END Peer1 - Adding  -->
